### ISSUE TITLE
Gradle Version Catalog

### ISSUE THREAD

**Issue by itssweetrain** [itssweetrain/daily-study#81]
# Gradle Version Catalog
프로젝트에서 사용되는 **의존성, 플러그인 등의 버전을 중앙에서 관리할 수 있도록 하는 방식.** 이를 통해 코드의 중복을 줄이고 프로젝트 전반에 걸쳐 의존성 관리를 더 쉽고 체계적으로 할 수 있다.

## 왜 Version Catalog 를 사용하나?
1. 의존성 버전 관리 일원화:
모든 의존성 버전을 한곳에서 관리하므로, 여러 모듈에서 중복된 의존성 선언을 피할 수 있다. 프로젝트 규모가 클수록 의존성 업데이트와 관리가 간편해진다.

2. 가독성과 유지보수성 향상:
이름과 별칭(alias)을 통해 의존성을 명확하고 읽기 쉽게 선언할 수 있다. libs라는 객체를 통해 의존성을 호출하여 가독성이 높아진다.

3. 중앙 집중식 업데이트:
버전 변경 시 하나의 파일만 수정하면 되므로 유지보수가 쉬워진다.

## Version Catalog 구성 요소
Version Catalog는 보통 `libs.versions.toml`이라는 파일에 정의되며, 이 파일은 다음과 같은 요소를 포함된다.

### Example
버전 선언 (versions): 의존성 버전을 지정한다.
```kotlin
[versions]
kotlin = "1.8.10"
coroutines = "1.6.4"
```

라이브러리 선언 (libraries): 라이브러리 의존성을 선언하고 이름(alias)을 지정한다.
```kotlin
[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
```

플러그인 선언 (plugins): 프로젝트에서 사용할 플러그인을 선언한다.
```kotlin
[plugins]
android = { id = "com.android.application", version = "8.1.0" }
```

버전 번들 (bundles): 관련된 의존성을 그룹으로 묶어서 관리할 수 있다.
```kotlin
[bundles]
ui = ["androidx.appcompat:appcompat", "com.google.android.material:material"]
```

### Example
1. settings.gradle에서 활성화:
프로젝트의 settings.gradle에서 Version Catalog를 활성화한다.
```
enableFeaturePreview('VERSION_CATALOGS')
```

2. libs.versions.toml 파일 추가: 보통 gradle 폴더 아래에 libs.versions.toml 파일을 생성하고 의존성을 정의한다.

3. 모듈에서 의존성 참조: 의존성 선언 시, libs 객체를 사용하여 참조한다.
```
dependencies {
    implementation(libs.kotlin.stdlib)
    implementation(libs.coroutines.core)
}
```

## toml
toml 은 간단한 구성으로 된 파일 포맷으로, 주로 설정 파일이나 데이터를 저장하는 데 사용한다. 키-쌍으로 구성되며, json이나 yaml과 같은 다른 형식들과 비교했을 때 간결하고 명확한 구조가 특징이다. Java, Python 등 다양한 언어에서 toml 파서를 지원한다. 

### Example
1. 키-값 쌍
```toml
title = "Example Config"
is_enabled = true
retries = 3
```

2. 테이블
```toml
[database] # Table 선언
server = "localhost"
port = 3306
enabled = true
```

3. 배열
```toml
fruits = ["apple", "banana", "cherry"]  # 문자열 배열
numbers = [1, 2, 3, 4, 5]               # 정수 배열
```

4. Nested Table (중첩 테이블)
```toml
[server]
address = "127.0.0.1"

[server.auth]
username = "admin"
password = "password123"
```

## 참고
https://blog.imqa.io/kotlin-dsl/
